services:
  mongo:
    image: mongo:6.0.9
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null --bind_ip_all
    
  jaeger:
    image: jaegertracing/all-in-one:1.32
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

volumes:
  mongo-data:
